compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_config_file: ds2.json
  #deepspeed_hostfile: /share/home/wg/TE/BLD/hostfile
  deepspeed_multinode_launcher: pdsh
  #zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

#main_process_ip: 10.250.128.75
#main_process_port: 9009
num_machines: 1
num_processes: 8